import './style.css';
import { createIcons, Wallet, ArrowUpRight, ArrowDownLeft, Plus, X, ChartNoAxesCombined, List, Settings, Download, Upload, ShieldCheck, ChevronRight, Search, Pencil, Trash2, RefreshCw, CircleHelp, ArrowLeft, Check, FileJson, Eye } from 'lucide';
import { Capacitor } from '@capacitor/core';
import { Filesystem, Directory, Encoding } from '@capacitor/filesystem';
import { Share } from '@capacitor/share';
import { D, emptyLedger, calculate, today, saveTrade, deleteTrade, validateLedger, parseBackup, backupText, demoLedger, money, signedMoney, quantity, orderedTrades, type Ledger, type Trade, type Quote } from './ledger';
import { store } from './storage';
const icons={Wallet,ArrowUpRight,ArrowDownLeft,Plus,X,ChartNoAxesCombined,List,Settings,Download,Upload,ShieldCheck,ChevronRight,Search,Pencil,Trash2,RefreshCw,CircleHelp,ArrowLeft,Check,FileJson,Eye};
const app=document.querySelector<HTMLDivElement>('#app')!, modalRoot=document.querySelector<HTMLDivElement>('#modal-root')!;
let data=emptyLedger(), realData=data, tab='holdings', filter='', sideFilter='all', demo=false, blocked=false, busy=false;
const esc=(v:unknown)=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const icon=(name:string)=>`<i data-lucide="${name}" aria-hidden="true"></i>`;
const tone=(v:ReturnType<typeof D>|undefined)=>v===undefined?'muted':v.gt(0)?'positive':v.lt(0)?'negative':'neutral';
function refreshIcons(){createIcons({icons,attrs:{'stroke-width':1.7}});}
function toast(text:string){const el=document.querySelector<HTMLDivElement>('#toast')!;el.textContent=text;el.classList.add('visible');setTimeout(()=>el.classList.remove('visible'),4000);}
function nav(){return [{id:'holdings',name:'持仓',icon:'wallet'},{id:'trades',name:'交易',icon:'list'},{id:'insights',name:'收益',icon:'chart-no-axes-combined'},{id:'settings',name:'备份',icon:'settings'}].map(x=>`<button class="nav-item ${tab===x.id?'active':''}" data-tab="${x.id}" ${tab===x.id?'aria-current="page"':''}>${icon(x.icon)}<span>${x.name}</span></button>`).join('');}
function empty(title:string,text:string,actions=true){return `<div class="empty">${icon('wallet')}<h3>${title}</h3><p>${text}</p>${actions?`<button class="primary" data-action="add">${icon('plus')}记录第一笔交易</button><button class="text-button" data-action="demo">先看看示例账本 ${icon('arrow-up-right')}</button>`:''}</div>`;}
function render(){
 const s=calculate(data); const titles:Record<string,string>={holdings:'我的持仓',trades:'交易记录',insights:'收益分析',settings:'数据与备份'};
 app.innerHTML=`<aside class="sidebar"><div class="brand"><span class="brand-icon">${icon('chart-no-axes-combined')}</span><div>持仓账本<small>STOCK LEDGER</small></div></div><nav>${nav()}</nav><div class="sidebar-foot">${icon('shield-check')}数据保存在本机<small>个人美股账本 · v1.0</small></div></aside>
 <div class="workspace">${demo?`<div class="demo-banner">${icon('eye')}示例模式 · 虚构交易与价格<button data-action="exit-demo">退出示例</button></div>`:''}
 <header><div><div class="eyebrow">YOUR PERSONAL PORTFOLIO</div><h1>${titles[tab]}</h1></div><div class="header-actions"><span class="currency">USD <span>美元</span></span>${tab!=='settings'?`<button class="primary" data-action="add">${icon('plus')}<span>记一笔</span></button>`:''}</div></header>
 ${blocked?`<div class="warning">本机账本无法读取，写入已暂停。请在备份页导入有效备份恢复。</div>`:''}
 <main>${tab==='holdings'?holdings(s):tab==='trades'?trades(s):tab==='insights'?insights(s):settings()}</main><footer>本机保存 <span>·</span> 美元计价 <span>·</span> 移动平均成本</footer></div><nav class="bottom-nav">${nav()}</nav>`;
 app.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab!;filter='';render();window.scrollTo(0,0);});
 app.querySelectorAll<HTMLButtonElement>('[data-action="add"]').forEach(b=>{b.disabled=blocked;b.onclick=()=>tradeModal();});
 app.querySelectorAll<HTMLButtonElement>('[data-action="demo"]').forEach(b=>b.onclick=()=>{realData=data;demo=true;data=demoLedger();tab='holdings';render();window.scrollTo(0,0);});
 app.querySelectorAll<HTMLButtonElement>('[data-action="exit-demo"]').forEach(b=>b.onclick=()=>{demo=false;data=realData;render();window.scrollTo(0,0);});
 app.querySelectorAll<HTMLButtonElement>('[data-quote]').forEach(b=>b.onclick=()=>quoteModal(b.dataset.quote!));
 app.querySelectorAll<HTMLButtonElement>('[data-edit]').forEach(b=>b.onclick=()=>tradeModal(data.trades.find(t=>t.id===b.dataset.edit)!));
 app.querySelectorAll<HTMLButtonElement>('[data-delete]').forEach(b=>b.onclick=()=>deleteModal(data.trades.find(t=>t.id===b.dataset.delete)!));
 const search=app.querySelector<HTMLInputElement>('#search');if(search)search.oninput=()=>{const pos=search.selectionStart;filter=search.value;render();const n=app.querySelector<HTMLInputElement>('#search')!;n.focus();n.setSelectionRange(pos,pos);};
 app.querySelectorAll<HTMLButtonElement>('[data-side-filter]').forEach(b=>b.onclick=()=>{sideFilter=b.dataset.sideFilter!;render();});
 const ex=app.querySelector<HTMLButtonElement>('#export');if(ex)ex.onclick=()=>void exportBackup();
 const im=app.querySelector<HTMLInputElement>('#import');if(im)im.onchange=()=>void importFile(im.files?.[0]);
 refreshIcons();
}
function holdings(s:ReturnType<typeof calculate>){return `
 <section class="overview"><div class="hero"><div class="hero-label">持仓市值 <span>USD</span></div><div class="hero-number" data-testid="market-value">${money(s.value)}</div><div class="hero-bottom"><div><span>浮动收益</span><strong class="${tone(s.unrealized)}" data-testid="unrealized">${signedMoney(s.unrealized)}</strong></div><div><span>持有股票</span><strong>${s.open.length}<small> 只</small></strong></div></div><div class="hero-watermark">${icon('chart-no-axes-combined')}</div></div>
 <div class="stat-stack"><div class="stat-card"><div class="stat-label">持仓成本 ${icon('wallet')}</div><strong data-testid="cost">${money(s.cost)}</strong><small>买入手续费已计入成本</small></div><div class="stat-card"><div class="stat-label">累计已实现收益 ${icon('arrow-up-right')}</div><strong class="${tone(s.realized)}" data-testid="realized">${signedMoney(s.realized)}</strong><small>卖出手续费已扣除</small></div></div></section>
 ${s.missing.length?`<div class="notice">${icon('circle-help')}<div>${s.missing.length} 只股票待填写股价<small>补全后显示总市值和浮动收益。</small></div><button class="text-button" data-quote="${esc(s.missing[0].symbol)}">去更新 ${icon('chevron-right')}</button></div>`:''}
 <section class="panel"><div class="section-heading"><h2>持仓明细 <span>${s.open.length}</span></h2><span class="caption">股价手动维护</span></div>
 ${!s.open.length?empty(data.trades.length?'当前没有持仓':'从第一笔投资开始',data.trades.length?'已平仓收益仍保留在收益页，随时记录下一笔交易。':'记录买入和卖出，让每一笔投资都有迹可循。'): `<div class="holding-grid">${s.open.map((p,i)=>`<article class="holding-card"><div class="holding-title"><span class="ticker-icon color-${i%4}">${esc(p.symbol.slice(0,1))}</span><div><h3>${esc(p.symbol)}</h3><small>${quantity(p.quantity)} 股</small></div><button class="icon-button" aria-label="更新 ${esc(p.symbol)} 股价" data-quote="${esc(p.symbol)}">${icon('pencil')}</button></div><div class="holding-value">${money(p.value)}</div><div class="profit-line ${tone(p.unrealized)}">${signedMoney(p.unrealized)} <span>${p.unrealized && p.cost.gt(0)?`(${p.unrealized.div(p.cost).mul(100).toFixed(2)}%)`:'浮动收益'}</span></div><div class="holding-details"><div><span>平均成本</span><b>${money(p.average)}</b></div><div><span>持仓成本</span><b>${money(p.cost)}</b></div><div><span>手动股价</span><b>${p.quote?money(p.quote.price):'待更新'}</b></div></div><button class="quote-date" data-quote="${esc(p.symbol)}">${icon('refresh-cw')}${p.quote?`${esc(p.quote.date)} 的手动报价`:'填写股价，查看浮动收益'}${icon('chevron-right')}</button></article>`).join('')}</div>`}</section>`;}
function trades(s:ReturnType<typeof calculate>){const list=orderedTrades(data.trades).reverse().filter(t=>(sideFilter==='all'||t.side===sideFilter)&&`${t.symbol} ${t.note}`.toLowerCase().includes(filter.toLowerCase()));return `<section class="panel"><div class="section-heading"><h2>全部交易 <span>${data.trades.length}</span></h2></div><div class="tools"><div class="segmented">${[['all','全部'],['buy','买入'],['sell','卖出']].map(([id,text])=>`<button data-side-filter="${id}" class="${id===sideFilter?'selected':''}">${text}</button>`).join('')}</div><label class="search">${icon('search')}<input id="search" value="${esc(filter)}" placeholder="搜索代码或备注" aria-label="搜索交易"></label></div>
 ${!data.trades.length?empty('还没有交易记录','添加买卖记录后，持仓和收益会自动更新。'):!list.length?empty('没有找到交易','试试其他股票代码或筛选条件。',false):`<div class="trade-list">${list.map(t=>{const gross=D(t.quantity).mul(t.price),net=t.side==='buy'?gross.plus(t.fee):gross.minus(t.fee);return `<article class="trade-row"><div class="trade-top"><span class="trade-icon ${t.side}">${icon(t.side==='buy'?'arrow-down-left':'arrow-up-right')}</span><div class="trade-name"><h3>${esc(t.symbol)} <span class="badge ${t.side}">${t.side==='buy'?'买入':'卖出'}</span></h3><small>${t.date} · 顺序 ${t.sequence+1}</small></div><div class="trade-amount"><strong>${money(gross)}</strong><small>成交金额</small></div></div><div class="trade-detail"><span>${quantity(t.quantity)} 股 × ${money(t.price)}</span><span>手续费 ${money(t.fee)}</span></div><div class="trade-detail"><span>${t.side==='buy'?'实际支出':'实际收入'} ${money(net)}</span>${t.side==='sell'?`<span class="${tone(s.gains.get(t.id))}">已实现 ${signedMoney(s.gains.get(t.id))}</span>`:''}</div>${t.note?`<p class="trade-note">${esc(t.note)}</p>`:''}<div class="trade-actions"><button class="text-button" data-edit="${esc(t.id)}">${icon('pencil')}编辑</button><button class="text-button delete" data-delete="${esc(t.id)}">${icon('trash-2')}删除</button></div></article>`;}).join('')}</div>`}<p class="panel-footnote">按交易日期计算；同一天按录入顺序计算。成交金额 = 股数 × 单价。</p></section>`;}
function insights(s:ReturnType<typeof calculate>){return `<section class="panel profit-summary"><div class="eyebrow">INVESTMENT RETURN</div><h2>累计投资收益</h2><div class="summary-number ${tone(s.totalProfit)}">${signedMoney(s.totalProfit)}</div><p>已实现收益 + 当前持仓浮动收益</p><div class="summary-split"><div><span>已实现收益</span><strong class="${tone(s.realized)}">${signedMoney(s.realized)}</strong></div><div><span>浮动收益</span><strong class="${tone(s.unrealized)}">${signedMoney(s.unrealized)}</strong></div></div>${s.missing.length?'<p class="notice-inline">部分股票缺少股价，累计收益暂未计算。</p>':''}</section><div class="two-columns"><section class="panel"><div class="section-heading"><h2>持仓成本分布</h2><span class="caption">按成本占比</span></div>${!s.open.length?'<p class="small-empty">暂无持仓</p>':s.open.map((p,i)=>{const pc=p.cost.div(s.cost).mul(100).toFixed(1);return `<div class="allocation"><div><b>${esc(p.symbol)}</b><span>${pc}% <small>${money(p.cost)}</small></span></div><div class="bar"><div class="color-${i%4}" style="width:${pc}%"></div></div></div>`;}).join('')}</section><section class="panel"><div class="section-heading"><h2>资金记录</h2></div><dl class="totals"><div><dt>累计买入支出</dt><dd>${money(s.buyTotal)}</dd></div><div><dt>累计卖出收入</dt><dd>${money(s.sellTotal)}</dd></div><div><dt>累计手续费</dt><dd>${money(s.fees)}</dd></div><div><dt>交易笔数</dt><dd>${data.trades.length} 笔</dd></div></dl><p class="panel-footnote">买入支出含手续费；卖出收入已扣手续费。这些是交易现金流，不代表账户现金余额。</p></section></div><section class="panel"><div class="section-heading"><h2>各股票已实现收益</h2></div>${!s.positions.length?'<p class="small-empty">卖出后可在这里查看收益</p>':s.positions.map(p=>`<div class="realized-row"><b>${esc(p.symbol)} <small>${p.quantity.eq(0)?'已平仓':'持仓中'}</small></b><strong class="${tone(p.realized)}">${signedMoney(p.realized)}</strong></div>`).join('')}</section>`;}
function settings(){return `<section class="panel backup-intro"><span class="large-icon">${icon('shield-check')}</span><h2>你的投资，由你保管</h2><p>账本保存在本机，无需注册。<br>定期导出一份备份，换手机也能接着记。</p><div class="backup-count"><span><strong>${data.trades.length}</strong> 笔交易</span><span><strong>${data.quotes.length}</strong> 条手动报价</span></div></section><section class="panel"><div class="section-heading"><h2>备份与恢复</h2></div><button class="setting-row" id="export" ${blocked||demo?'disabled':''}><span class="setting-icon">${icon('download')}</span><span><b>导出完整备份</b><small>保存 JSON 文件，包含交易、报价与备注</small></span>${icon('chevron-right')}</button><label class="setting-row ${demo?'disabled':''}" for="import"><span class="setting-icon">${icon('upload')}</span><span><b>从备份恢复</b><small>先预览文件内容，再确认替换当前账本</small></span>${icon('chevron-right')}<input id="import" type="file" accept=".json,application/json" ${demo?'disabled':''} class="visually-hidden"></label><p class="panel-footnote">备份文件是未加密的个人账本，请存放在你信任的位置。卸载应用会删除本机数据，卸载前请先导出。</p></section><section class="panel"><div class="section-heading"><h2>计算说明</h2></div><div class="rules"><h3>移动平均成本</h3><p>买入金额和手续费加入持仓成本；卖出按卖出前的平均成本扣减。已实现收益为卖出金额减手续费，再减去卖出部分的成本。</p><h3>股价与时间</h3><p>此版本手动填写股价，并显示报价日期；不连接实时行情。支持小数股。修改历史交易后，按日期和同日录入顺序重新计算所有持仓。</p><h3>第一版范围</h3><p>支持美元股票的买入、卖出与手动报价，最多 5,000 笔交易。暂不包含分红、拆股、做空、期权或税务成本计算。</p></div></section>${demo?'':`<button class="secondary full" data-action="demo">${icon('eye')}查看示例账本</button>`}`;}
let previousFocus:HTMLElement|null=null;
function modal(title:string,body:string){previousFocus=document.activeElement as HTMLElement;modalRoot.innerHTML=`<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="dialog-title" tabindex="-1"><div class="modal-head"><h2 id="dialog-title">${title}</h2><button class="icon-button" id="close-modal" aria-label="关闭">${icon('x')}</button></div>${body}</section></div>`;document.body.classList.add('modal-open');modalRoot.querySelector<HTMLButtonElement>('#close-modal')!.onclick=closeModal;modalRoot.querySelector<HTMLElement>('.modal')!.focus();refreshIcons();}
function closeModal(){if(busy)return;modalRoot.innerHTML='';document.body.classList.remove('modal-open');previousFocus?.focus();}
document.addEventListener('keydown',e=>{if(!modalRoot.children.length)return;if(e.key==='Escape')closeModal();if(e.key==='Tab'){const items=[...modalRoot.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),textarea,select,[tabindex="0"]')];const first=items[0],last=items[items.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===modalRoot.querySelector('.modal'))){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});
async function commit(next:Ledger){if(demo){data=next;return;}await store.save(next);data=next;realData=next;}
async function submit(work:()=>Promise<void>){if(busy)return;busy=true;modalRoot.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=true);const error=modalRoot.querySelector<HTMLElement>('#form-error');if(error)error.textContent='';try{await work();busy=false;closeModal();render();toast(demo?'示例账本已更新，真实数据未改变':'已保存到本机');}catch(e){if(error)error.textContent=e instanceof Error?e.message:'保存失败，请重试。';else toast(String(e));}finally{busy=false;modalRoot.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=false);}}
function tradeModal(t?:Trade){if(blocked)return;const sequence=t?.sequence??(Math.max(-1,...data.trades.map(x=>x.sequence))+1);modal(t?'编辑交易':'记录交易',`<form id="trade-form"><div class="form-tabs"><label><input name="side" type="radio" value="buy" ${!t||t.side==='buy'?'checked':''}><span>买入</span></label><label><input name="side" type="radio" value="sell" ${t?.side==='sell'?'checked':''}><span>卖出</span></label></div><div class="form-grid"><label>股票代码<input name="symbol" placeholder="例如 AAPL" maxlength="15" autocapitalize="characters" autocomplete="off" required value="${esc(t?.symbol??'')}"></label><label>交易日期<input name="date" type="date" min="1900-01-01" max="${today()}" required value="${t?.date??today()}"></label><label>成交股数<input name="quantity" inputmode="decimal" placeholder="支持小数股" required value="${t?.quantity??''}"></label><label>成交单价（美元）<input name="price" inputmode="decimal" placeholder="0.00" required value="${t?.price??''}"></label><label class="full-field">手续费（美元）<input name="fee" inputmode="decimal" required value="${t?.fee??'0'}"></label></div><div class="calculation-preview"><div><span>成交金额</span><strong id="gross">—</strong></div><div><span id="net-label">实际支出</span><strong id="net">—</strong></div></div><label class="note-field">备注 <span>选填</span><textarea name="note" maxlength="500" rows="2" placeholder="记录这次交易的想法…">${esc(t?.note??'')}</textarea></label><p class="form-hint">同一天按录入顺序计算${t?'；编辑保留原顺序':''}。</p><p id="form-error" class="form-error" role="alert"></p><button class="primary full" type="submit">${icon('check')}${t?'保存修改':'保存交易'}</button></form>`);
 const form=modalRoot.querySelector<HTMLFormElement>('#trade-form')!;const update=()=>{const f=new FormData(form);try{const gross=D(String(f.get('quantity'))).mul(String(f.get('price'))), fee=D(String(f.get('fee')));modalRoot.querySelector('#gross')!.textContent=money(gross);modalRoot.querySelector('#net')!.textContent=money(f.get('side')==='buy'?gross.plus(fee):gross.minus(fee));}catch{modalRoot.querySelector('#gross')!.textContent='—';modalRoot.querySelector('#net')!.textContent='—';}modalRoot.querySelector('#net-label')!.textContent=f.get('side')==='buy'?'实际支出（含费）':'实际收入（扣费后）';};form.oninput=update;update();form.onsubmit=e=>{e.preventDefault();void submit(async()=>{const f=new FormData(form),get=(k:string)=>String(f.get(k)??'').trim();const next=saveTrade(data,{id:t?.id??crypto.randomUUID(),sequence,symbol:get('symbol').toUpperCase(),side:get('side') as 'buy'|'sell',date:get('date'),quantity:get('quantity'),price:get('price'),fee:get('fee'),note:get('note')});await commit(next);});};
}
function quoteModal(symbol:string){if(blocked)return;const q=data.quotes.find(q=>q.symbol===symbol);modal(`更新 ${esc(symbol)} 股价`,`<form id="quote-form"><p class="form-hint">填写你查到的价格，用于计算持仓市值和浮动收益。</p><label class="note-field">股价（美元）<input name="price" inputmode="decimal" required value="${q?.price??''}" placeholder="0.00"></label><label class="note-field">报价日期<input type="date" name="date" min="1900-01-01" max="${today()}" required value="${today()}"></label><p id="form-error" class="form-error" role="alert"></p><button type="submit" class="primary full">保存股价</button></form>`);const f=modalRoot.querySelector<HTMLFormElement>('#quote-form')!;f.onsubmit=e=>{e.preventDefault();void submit(async()=>{const fd=new FormData(f);const quote:Quote={symbol,price:String(fd.get('price')).trim(),date:String(fd.get('date'))};await commit(validateLedger({...data,quotes:[...data.quotes.filter(x=>x.symbol!==symbol),quote]}));});};}
function deleteModal(t:Trade){modal('删除这笔交易？',`<p class="dialog-copy">${t.date} · ${esc(t.symbol)} · ${t.side==='buy'?'买入':'卖出'} ${quantity(t.quantity)} 股<br>删除后将重新计算全部持仓和收益。如果导致历史持仓不足，将无法删除。</p><p id="form-error" class="form-error" role="alert"></p><button class="danger full" id="confirm-delete">确认删除</button>`);modalRoot.querySelector<HTMLButtonElement>('#confirm-delete')!.onclick=()=>void submit(async()=>{await commit(deleteTrade(data,t.id));});}
async function exportBackup(){if(demo||blocked)return;const b=app.querySelector<HTMLButtonElement>('#export')!;b.disabled=true;try{const text=backupText(data),filename=`stock-ledger-${today()}-${Date.now()}.json`;if(Capacitor.isNativePlatform()){const result=await Filesystem.writeFile({path:filename,data:text,directory:Directory.Cache,encoding:Encoding.UTF8});await Share.share({title:'持仓账本备份',files:[result.uri],dialogTitle:'保存账本备份'});}else{const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}toast('备份文件已生成，请保存到安全位置');}catch(e){toast(`未完成导出：${e instanceof Error?e.message:String(e)}`);}finally{b.disabled=false;}}
async function importFile(file?:File){if(!file)return;try{if(file.size>8_000_000)throw Error('文件过大，请选择 8 MB 以内的 JSON 备份。');const next=parseBackup(await file.text());const s=calculate(next);modal('恢复这份备份？',`<div class="import-preview">${icon('file-json')}<b>${esc(file.name)}</b><p>${next.trades.length} 笔交易 · ${s.open.length} 只持仓 · ${next.quotes.length} 条报价</p><strong>持仓成本 ${money(s.cost)}</strong></div><p class="dialog-copy">确认后，此备份将替换当前的 ${data.trades.length} 笔交易。建议先导出当前账本。恢复前会保留上一份本机存储副本。</p><p id="form-error" class="form-error" role="alert"></p><button class="primary full" id="confirm-import">确认替换并恢复</button>`);modalRoot.querySelector<HTMLButtonElement>('#confirm-import')!.onclick=()=>void submit(async()=>{if(blocked){await store.recover(next);blocked=false;data=next;realData=next;}else await commit(next);});}catch(e){modal('无法导入备份',`<p class="form-error">${esc(e instanceof Error?e.message:String(e))}</p><p class="dialog-copy">当前账本未改变。</p>`);}finally{const i=app.querySelector<HTMLInputElement>('#import');if(i)i.value='';}}
async function start(){try{const loaded=await store.load();data=loaded.data;realData=data;if(loaded.recovered)toast('已从上一份本机副本恢复，请核对最近交易并导出备份。');}catch(e){blocked=true;tab='settings';toast(e instanceof Error?e.message:'存储打开失败');}render();}void start();
